/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChannelStatus = IDL.Record({
  'offlineChannels' : IDL.Nat,
  'liveChannels' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserStats = IDL.Record({
  'weeklyActiveUsers' : IDL.Nat,
  'monthlyActiveUsers' : IDL.Nat,
  'lifetimeUsers' : IDL.Nat,
});

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllChannelStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ChannelStatus))],
      ['query'],
    ),
  'getAllStatsSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalMonthlyActiveUsers' : IDL.Nat,
          'totalLifetimeUsers' : IDL.Nat,
          'totalWeeklyActiveUsers' : IDL.Nat,
          'totalStats' : IDL.Nat,
          'totalOfflineChannels' : IDL.Nat,
          'totalChannels' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalLiveChannels' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAllUserStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelStatus' : IDL.Func([], [IDL.Opt(ChannelStatus)], ['query']),
  'getChannelStatusForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ChannelStatus)],
      ['query'],
    ),
  'getTotalChannelCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalLifetimeUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalLiveChannels' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalMonthlyActiveUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalOfflineChannels' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalStatsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalWeeklyActiveUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
  'getUserStatsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserStats)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateChannelStatus' : IDL.Func([ChannelStatus], [], []),
  'updateUserStats' : IDL.Func([UserStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChannelStatus = IDL.Record({
    'offlineChannels' : IDL.Nat,
    'liveChannels' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserStats = IDL.Record({
    'weeklyActiveUsers' : IDL.Nat,
    'monthlyActiveUsers' : IDL.Nat,
    'lifetimeUsers' : IDL.Nat,
  });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllChannelStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ChannelStatus))],
        ['query'],
      ),
    'getAllStatsSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalMonthlyActiveUsers' : IDL.Nat,
            'totalLifetimeUsers' : IDL.Nat,
            'totalWeeklyActiveUsers' : IDL.Nat,
            'totalStats' : IDL.Nat,
            'totalOfflineChannels' : IDL.Nat,
            'totalChannels' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalLiveChannels' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAllUserStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserStats))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelStatus' : IDL.Func([], [IDL.Opt(ChannelStatus)], ['query']),
    'getChannelStatusForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ChannelStatus)],
        ['query'],
      ),
    'getTotalChannelCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalLifetimeUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalLiveChannels' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalMonthlyActiveUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalOfflineChannels' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalStatsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalWeeklyActiveUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
    'getUserStatsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserStats)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateChannelStatus' : IDL.Func([ChannelStatus], [], []),
    'updateUserStats' : IDL.Func([UserStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };