/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChannelStatus {
  'offlineChannels' : bigint,
  'liveChannels' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'weeklyActiveUsers' : bigint,
  'monthlyActiveUsers' : bigint,
  'lifetimeUsers' : bigint,
}
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllChannelStatuses' : ActorMethod<[], Array<[Principal, ChannelStatus]>>,
  'getAllStatsSummary' : ActorMethod<
    [],
    {
      'totalMonthlyActiveUsers' : bigint,
      'totalLifetimeUsers' : bigint,
      'totalWeeklyActiveUsers' : bigint,
      'totalStats' : bigint,
      'totalOfflineChannels' : bigint,
      'totalChannels' : bigint,
      'totalUsers' : bigint,
      'totalLiveChannels' : bigint,
    }
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllUserStats' : ActorMethod<[], Array<[Principal, UserStats]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelStatus' : ActorMethod<[], [] | [ChannelStatus]>,
  'getChannelStatusForUser' : ActorMethod<[Principal], [] | [ChannelStatus]>,
  'getTotalChannelCount' : ActorMethod<[], bigint>,
  'getTotalLifetimeUsers' : ActorMethod<[], bigint>,
  'getTotalLiveChannels' : ActorMethod<[], bigint>,
  'getTotalMonthlyActiveUsers' : ActorMethod<[], bigint>,
  'getTotalOfflineChannels' : ActorMethod<[], bigint>,
  'getTotalStatsCount' : ActorMethod<[], bigint>,
  'getTotalUserCount' : ActorMethod<[], bigint>,
  'getTotalWeeklyActiveUsers' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[], [] | [UserStats]>,
  'getUserStatsForUser' : ActorMethod<[Principal], [] | [UserStats]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateChannelStatus' : ActorMethod<[ChannelStatus], undefined>,
  'updateUserStats' : ActorMethod<[UserStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];